# TCL File Generated by Component Editor 18.1
# Thu Apr 30 20:14:05 CDT 2020
# DO NOT MODIFY


# 
# avalon_graphics_interface "Avalon Graphics Interface" v1.2
#  2020.04.30.20:14:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_graphics_interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_graphics_interface
set_module_property VERSION 1.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon Graphics Interface"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_graphics_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_graphics_interface.sv SYSTEM_VERILOG PATH avalon_graphics_interface.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_graphics_interface.sv SYSTEM_VERILOG PATH avalon_graphics_interface.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock Clk
set_interface_property avalon_slave associatedReset RESET
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave AVL_ADDR address Input 4
add_interface_port avalon_slave AVL_CS chipselect Input 1
add_interface_port avalon_slave AVL_BYTE_EN byteenable Input 4
add_interface_port avalon_slave AVL_READ read Input 1
add_interface_port avalon_slave AVL_READDATA readdata Output 32
add_interface_port avalon_slave AVL_WRITE write Input 1
add_interface_port avalon_slave AVL_WRITEDATA writedata Input 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Clk
# 
add_interface Clk clock end
set_interface_property Clk clockRate 50000000
set_interface_property Clk ENABLED true
set_interface_property Clk EXPORT_OF ""
set_interface_property Clk PORT_NAME_MAP ""
set_interface_property Clk CMSIS_SVD_VARIABLES ""
set_interface_property Clk SVD_ADDRESS_GROUP ""

add_interface_port Clk Clk clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock Clk
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point VGA_DATA
# 
add_interface VGA_DATA conduit end
set_interface_property VGA_DATA associatedClock Clk
set_interface_property VGA_DATA associatedReset ""
set_interface_property VGA_DATA ENABLED true
set_interface_property VGA_DATA EXPORT_OF ""
set_interface_property VGA_DATA PORT_NAME_MAP ""
set_interface_property VGA_DATA CMSIS_SVD_VARIABLES ""
set_interface_property VGA_DATA SVD_ADDRESS_GROUP ""

add_interface_port VGA_DATA VGA_B vga_b Output 8
add_interface_port VGA_DATA VGA_R vga_r Output 8
add_interface_port VGA_DATA VGA_G vga_g Output 8
add_interface_port VGA_DATA VGA_SYNC_N vga_sync_n Output 1
add_interface_port VGA_DATA VGA_CLK vga_clk Output 1
add_interface_port VGA_DATA VGA_BLANK_N vga_blank_n Output 1
add_interface_port VGA_DATA VGA_VS vga_vs Output 1
add_interface_port VGA_DATA VGA_HS vga_hs Output 1


# 
# connection point SRAM_DATA
# 
add_interface SRAM_DATA conduit end
set_interface_property SRAM_DATA associatedClock Clk
set_interface_property SRAM_DATA associatedReset ""
set_interface_property SRAM_DATA ENABLED true
set_interface_property SRAM_DATA EXPORT_OF ""
set_interface_property SRAM_DATA PORT_NAME_MAP ""
set_interface_property SRAM_DATA CMSIS_SVD_VARIABLES ""
set_interface_property SRAM_DATA SVD_ADDRESS_GROUP ""

add_interface_port SRAM_DATA SRAM_DQ sram_dq Bidir 16
add_interface_port SRAM_DATA SRAM_UB_N sram_ub_n Output 1
add_interface_port SRAM_DATA SRAM_LB_N sram_lb_n Output 1
add_interface_port SRAM_DATA SRAM_CE_N sram_ce_n Output 1
add_interface_port SRAM_DATA SRAM_OE_N sram_oe_n Output 1
add_interface_port SRAM_DATA SRAM_WE_N sram_we_n Output 1
add_interface_port SRAM_DATA SRAM_ADDRESS sram_address Output 20

